import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { FormControl } from "@angular/forms";

@Component({
  selector: 'app-searchbar',
  templateUrl: './searchbar.component.html',
  styleUrls: ['./searchbar.component.css']
})
export class SearchbarComponent implements OnInit {

  stockName;
  myControl = new FormControl();
  symbols;
  query:string = '';

  constructor(private router: Router) {
    this.loadSymbols();
  }


  ngOnInit() {

  }

  // onKey(event:any){
  //   if(event.target.value == '' || event.target.value == null){
  //     this.router.navigate(['/home']);
  //   } else{
  //     this.options = this.sampleList.filter((element) => {
  //       element = event.target.value
  //       return this.stockName = element.toLocaleUpperCase();
  //     })
  //   }
  // }





  //build list of states as map of key-value pairs
  loadSymbols() {
    // var allSymbols = 'Alabama, Alaska, Arizona, Arkansas, California, Colorado, Connecticut, Delaware,\
    //    Florida, Georgia, Hawaii, Idaho, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisiana,\
    //    Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana,\
    //    Nebraska, Nevada, New Hampshire, New Jersey, New Mexico, New York, North Carolina,\
    //    North Dakota, Ohio, Oklahoma, Oregon, Pennsylvania, Rhode Island, South Carolina,\
    //    South Dakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, West Virginia,\
    //    Wisconsin, Wyoming';

    var allSym = 'AA, AAN, AAP, AAT, AB, ABB, ABBV, ABC, ABEV, ABG, ABM, ABR, ABT, AC, ACA, ACB, ACC, ACCO, ACEL, ACH, ACM, ACN, ACP, ACRE, ACV,\
      ADC, ADCT, ADM, ADNT, ADS, ADSW, ADT, ADX, AEB, AEE, AEFC, AEG, AEL, AEM, AEO, AEP, AER, AES, AFB, AFC, AFG, AFGB, AFGC, AFGH, AFI,\
      AFL, AFT, AG, AGCO, AGD, AGI, AGM, AGO, AGR, AGRO, AGS, AGX, AHC, AHH, AHT, AI, AIC, AIF,AIG, AIN, AIO, AIR, AIT, AIV, AIW, AIZ, AIZP,\
      AJG, AJRD, AJX, AJXA, AKR, AL, ALB, ALC, ALE, ALEX, ALG,ALK, ALL, ALLE, ALLY, ALSN, ALTG, ALUS, ALV, ALX, AM, AMBC, AMC, AMCR, AME, AMG,\
      AMH, AMK, AMN, AMOV, AMP, AMPY, AMRC, AMRX, AMT, AMX, AN, ANET, ANF, ANH, ANTM, AOD, AON, AOS, AP, APA, APAM, APD, APG, APH, APHA, APLE,\
      APO, APRN, APTS, APTV, APY, AQN, AQNA, AQNB, AQUA, AR, ARA, ARC, ARCH, ARCO,ARD, ARDC, ARE, ARES, ARGD, ARGO, ARI, ARL, ARLO, ARMK, ARNC,\
      AROC, ARR, ARW, ASA, ASB, ASC, ASG, ASGN, ASH, ASIX, ASPN, ASR, ASX, AT, ATCO, ATEN,ATGE, ATH, ATHM, ATI, ATKR, ATO, ATR, ATTO, ATUS, ATV,\
      AU, AUY, AVA, AVAL, AVB, AVD, AVK, AVLR, AVNS, AVTR, AVY, AVYA, AWF, AWI, AWK, AWP, AWR, AX, AXE, AXL, AXO, AXP, AXR, AXS, AXTA, AYI, AYX, AZN, AZO, AZRE, AZUL, AZZ,\
      B,BA, BABA, BAC, BAF, BAH, BAK, BAM, BANC, BAP, BAX, BB, BBAR, BBD, BBDC, BBDO, BBF, BBK, BBL, BBN, BBU, BBVA, BBW, BBX, BBY, BC, BCC,BCE, BCEI, BCH, BCO, BCS, BCSF,\
      BCX, BDC, BDJ, BDN, BDX, BE, BEDU, BEN, BEP, BERY, BEST, BFAM, BFK, BFO, BFS, BFY, BFZ, BG, BGB, BGG, BGH, BGIO, BGR, BGS, BGSF, BGT, BGX, BGY,BH, BHC, BHE, BHK, BHLB,\
      BHP, BHR, BHV, BHVN,BIF, BIG, BILL, BIO, BIP, BIPC, BIT, BITA, BJ, BK, BKD, BKE, BKH, BKI, BKK, BKN, BKR, BKT, BKU, BLD, BLE, BLK, BLL, BLW, BLX,\
      BMA, BME, BMEZ, BMI, BMO, BMY, BNED, BNS, BNY, BOE, BOH, BOOT, BORR, BOX, BP, BPMP, BPT, BQH, BR, BRBR, BRC, BRFS, BRMK, BRO, BRT, BRX, BSA, BSAC,\
      BSBR, BSD, BSE, BSIG, BSL, BSM, BSMX, BST, BSTZ, BSX, BTA, BTE, BTI, BTO, BTT, BTU, BTZ, BUD, BUI, BURL, BV, BVN, BW, BWA, BWG, BWXT, BX, BXC, BXG, BXMT, BXMX, BXP, BXS, BY, BYD, BYM, BZH, BZM,\
      C, CAAP, CABO, CACI, CADE, CAE, CAF, CAG, CAH, CAI, CAJ, CAL, CALX, CANG, CAPL, CARR, CARS, CAT, CATO, CB, CBB, CBD, CBH, CBL, CBO, CBRE, CBT, CBU, CBX,\
      CBZ, CC, CCAC, CCC, CCEP, CCH, CCI, CCJ, CCK, CCL, CCM, CCO, CCR, CCS, CCU, CCX, CCXX, CCZ, CDAY, CDE, CDR, CE, CEA, CEE, CEIX, CEL, CELG~, CELP, CEM, CEN,\
      CEO, CEPU, CEQP, CF, CFG, CFR, CFX, CFXA, CGA, CGC, CHA, CHAP, CHCT, CHD, CHE, CHGG, CHH, CHK, CHL, CHMI, CHN, CHRA, CHS, CHT, CHU, CHWY, CI, CIA, CIB,\
      CIEN, CIF, CIG, CII, CIM, CINR, CIO, CIR, CIT, CKH, CL, CLB, CLDR, CLDT, CLF, CLGX, CLH, CLI, CLNC, CLNY, CLPR, CLR, CLS, CLW, CLX, CM, CMA, CMC, CMCM,\
      CMD, CMG, CMI, CMO, CMP, CMRE, CMS, CMSA, CMSC, CMSD, CMU, CNA, CNC, CNF, CNHI, CNI, CNK, CNMD, CNNE, CNO, CNP, CNQ, CNR, CNS, CNX, CNXM, CO, CODI,\
      COE, COF, COG, COLD, COO, COP, COR, CORR, COTY, CP, CPA, CPAC, CPB, CPE, CPF, CPG, CPK, CPLG, CPRI, CPS, CPT, CR, CRC, CRH, CRI, CRK, CRL, CRM, CRS,\
      CRT, CRY, CS, CSL, CSLT, CSPR, CSTM, CSU, CSV, CTAA, CTB, CTBB, CTDD, CTEST, CTK, CTL, CTLT, CTR, CTRA, CTS, CTT , CTV, CTVA, CTY, CTZ, CUB, CUBB, CUBE,\
      CUBI, CUK, CULP, CURO, CUZ, CVA, CVE, CVEO, CVI, CVIA, CVNA, CVS, CVX, CW, CWEN, CWH, CWK, CWT, CX, CXE, CXH, CXO, CXP, CXW, CYD, CYH, CZZ,\
      D, DAC, DAL, DAN, DAO, DAR, DAVA, DB, DBD, DBI, DBL, DCF, DCI, DCO, DCP, DCUE, DD, DDD, DDF, DDS, DDT, DE, DEA, DECK, DEI, DELL, DEO, DESP,\
      DEX, DFIN, DFNS, DFP, DFS, DG, DGX, DHF, DHI, DHR, DHT, DHX, DIAX, DIN, DIS, DK, DKL, DKS, DL, DLB, DLNG, DLPH, DLR, DLX, DLY, DMB, DMO, DMYT,\
      DNI, DNK, DNOW, DNP, DNR, DOC, DOOR, DOV, DOW, DPG, DPZ, DQ, DRD, DRE, DRH, DRI, DRQ, DRUA, DS, DSE, DSL, DSM, DSSI, DSU, DSX, DT, DTE, DTF,\
      DTJ, DTP, DTQ, DTW, DTY, DUC, DUK, DUKB, DUKH, DVA, DVD, DVN, DX, DXC, DY,\
      E, EAB, EAE, EAF, EAI, EARN, EAT, EB, EBF, EBR, EBS, EC, ECC , ECCB, ECCX, ECCY, ECL, ECOM , ECT, ED, EDD, EDF, EDI, EDN, EDU, EE, EEA, EEX,\
      EFC, EFF, EFL, EFR, EFT, EFX, EGF, EGHT, EGIF, EGO, EGP, EGY, EHC, EHI, EHT, EIC, EIG, EIX, EL, ELAN, ELAT, ELC, ELF, ELJ, ELP, ELS, ELU,\
      ELVT, ELY, EMD, EME, EMF, EMN, EMO, EMP, EMR, ENB, ENBA, ENBL, ENIA, ENIC, ENJ, ENLC, ENO, ENR, ENS, ENV, ENVA, ENZ, EOD, EOG, EOI, EOS,\
      EOT, EPAC, EPAM, EPC, EPD, EPR, EPRT, EQC, EQH, EQM, EQNR, EQR, EQS, EQT, ERA, ERF, ERJ, EROS, ES, ESE, ESI, ESNT, ESRT, ESS, ESTC, ESTE,\
      ET, ETB, ETG, ETH, ETJ, ETM, ETN, ETO, ETR, ETRN, ETV, ETW, ETX, ETY, EURN, EV, EVA, EVC, EVF, EVG, EVH, EVN, EVR, EVRG, EVRI, EVT, EVTC,\
      EW, EXD, EXG, EXK, EXP, EXPR, EXR, EXTN, EZT,\
      F, FAF, FAM, FBC, FBHS, FBK, FBM, FBP, FC, FCAU, FCF, FCN, FCPT, FCT, FCX, FDEU, FDP, FDS, FDX, FE, FEAC, FEDU, FEI, FENG, FEO, FET, FF, FFA,\
      FFC, FFG, FG, FGB, FHI, FHN, FI, FICO, FIF, FINS, FINV, FIS, FIT, FIV, FIX, FL, FLC, FLNG, FLO, FLOW, FLR, FLS, FLT, FLY, FMC, FMN, FMO, FMS,\
      FMX, FMY, FN, FNB, FND, FNF, FNV, FOE, FOF, FOR, FPAC, FPF, FPH, FPI, FPL, FR, FRA, FRC, FRO, FRT, FSB, FSD, FSK, FSLF, FSLY, FSM, FSS, FT, FTAI,\
      FTCH, FTI, FTK, FTS, FTV, FUL, FUN, FVRR, \
      G, GAB, GAM, GATX, GBAB, GBL, GBX, GCAP, GCI, GCO, GCP, GCV, GD, GDDY, GDL, GDO, GDOT, GDV, GE, GEF, GEL, GEN , GEO, GER, GES, GF, GFF, GFI, GFL,\
      GFLU, GFY, GGB, GGG, GGM, GGT, GGZ, GHC, GHG, GHL, GHM, GHY, GIB, GIL, GIM, GIS, GIX, GIX~, GJH, GJO, GJP, GJR, GJS, GJT, GKOS, GL, GLEO, GLOB,\
      GLOG, GLOP, GLP, GLT, GLW, GM, GME, GMED, GMRE, GMS, GMTA, GMZ, GNC, GNE, GNK, GNL, GNRC, GNT, GNW, GOF, GOL, GOLD, GOLF, GOOS, GPC, GPI, GPJA,\
      GPK, GPM, GPMT, GPN, GPRK, GPS, GPX, GRA, GRAF, GRAM, GRC, GRUB, GRX, GS, GSBD, GSH, GSK, GSL, GSLD, GSX, GTES, GTN, GTS, GTT, GTX, GTY, GUT, GVA, GWB, GWRE, GWW, GYC,\
      H, HAE, HAL, HASI, HBB, HBI, HBM, HCA, HCC, HCFT, HCHC, HCI, HCR, HCXY, HCXZ, HD, HDB, HE, HEI, HEP, HEQ, HES, HESM, HEXO, HFC, HFRO, HGH, HGLB,\
      HGV, HHC, HHS, HI, HIE, HIG, HII, HIL, HIO, HIW, HIX, HKIB, HL, HLF, HLI, HLT, HLX, HMC, HMI, HMLP, HMN, HMY, HNGR, HNI, HNP, HOG, HOME, HON, HOV,\
      HP, HPE, HPF, HPI, HPP, HPQ, HPR, HPS, HQH, HQL, HR, HRB, HRC, HRI, HRL, HRTG, HSBC, HSC, HST, HSY, HT, HTA, HTD, HTFA, HTGC, HTH, HTY, HTZ, HUBB,\
      HUBS, HUD, HUM, HUN, HUYA, HVT, HWM, HXL, HY, HYB, HYI, HYT, HZN, HZO,\
      IAA, IAE, IAG, IBA, IBM, IBN, IBP, ICD, ICE, ICL, IDA, IDE, IDT, IEX, IFF, IFFT, IFN, IFS, IGA, IGD, IGI, IGR, IGT, IHC, IHD, IHG, IHIT, IHTA, IID,\
      IIF, IIM, IIPR, IMAX, INFO, INFY, ING, INGR, INN, INSI, INSP, INSW, INT, INVH, IO, IP, IPG, IPHI, IPI, IPV, IQI, IQV, IR, IRET, IRL, IRM, IRR, IRS,\
      IRT, ISD, IT, ITCB, ITGR, ITT, ITUB, ITW, IVC, IVH, IVR, IVZ, IX,\
      J, JAX, JBGS, JBK, JBL, JBT, JCAP, JCE, JCI, JCO, JDD, JE, JEF, JELD, JEMD, JEQ, JFR, JGH, JHAA, JHB, JHG, JHI, JHS, JHX, JHY, JIH, JILL, JKS,\
      JLL, JLS, JMIA, JMM, JMP, JNJ, JNPR, JOE, JOF, JP, JPC, JPI, JPM, JPS, JPT, JQC, JRI, JRO, JRS, JSD, JT, JTA, JTD, JWN,\
      K, KAI, KAMN, KAR, KB, KBH, KBR, KDMN, KDP, KEM, KEN, KEP, KEX, KEY, KEYS, KF, KFS, KFY, KGC, KIM, KIO, KKR, KL, KMB, KMF,\
      KMI, KMPR, KMT, KMX, KN, KNL, KNOP, KNX, KO, KODK, KOF, KOP, KOS, KR, KRA, KRC, KREF, KRG, KRO, KRP, KSM, KSS, KSU, KT, KTB, KTF, KTH, KTN, KW, KWR, KYN,\
      L, LAC, LAD, LADR, LAIX, LAZ, LB, LBRT, LC, LCI, LCII, LDL, LDOS, LDP, LEA, LEAF, LEE, LEG, LEJU, LEN, LEO, LEVI, LFC, LGC, LGI, LH, LHC, LHX, LII, LIN,\
      LINX, LITB, LL, LLY, LM, LMHA, LMHB, LMT, LN, LNC, LND, LNN, LOMA, LOW, LPG, LPI, LPL, LPX, LRN, LSI, LTC, LTHM, LTM, LUB, LUV, LVS, LW, LXFR, LXP, LXU, LYB, LYG, LYV, LZB,\
      M, MA, MAA, MAC, MAIN, MAN, MANU, MAS, MATX, MAV, MAXR, MBI, MBT, MC, MCA, MCB, MCC, MCD, MCI, MCK, MCN, MCO, MCR, MCS, MCV, MCX, MCY, MD, MDC, MDLA, MDLQ,\
      MDLX, MDLY, MDP, MDT, MDU, MEC, MED, MEI, MEN, MET, MFA, MFAC, MFC, MFD, MFG, MFGP, MFL, MFM, MFO, MFT, MFV, MG, MGA, MGF, MGM, MGP, MGR, MGU, MGY, MHD,\
      MHE, MHF, MHI, MHK, MHLA, MHN, MHNC, MHO, MIC, MIE, MIN, MITT, MITTA, MIXT, MIY, MKC, MKL, MLI, MLM, MLP, MLR, MMC, MMD, MMI, MMM, MMP, MMS, MMT, MMU,\
      MN, MNE, MNK, MNP, MNR, MNRL, MO, MOD, MODN, MOGU, MOH, MOS, MOV, MPA, MPC, MPLX, MPV, MPW, MPX, MQT, MQY, MR, MRC, MRK, MRO, MS, MSA, MSB, MSC, MSCI,\
      MSD, MSGE, MSGN, MSGS, MSI, MSM, MT, MTB, MTCN, MTD, MTDR, MTG, MTH, MTL, MTN, MTOR, MTR, MTRN, MTT, MTW, MTX, MTZ, MUA, MUC, MUE, MUFG, MUH, MUI, MUJ,\
      MUR, MUS, MUSA, MUX, MVC, MVCD, MVF, MVO, MVT, MWA, MX, MXE, MXF, MXL, MYC, MYD, MYE, MYF, MYI, MYJ, MYN, MYOV, MZA,\
      NAC, NAD, NAN, NAT, NAV, NAZ, NBB, NBHC, NBR, NC, NCA, NCB, NCLH, NCR, NCV, NCZ, NDP, NE, NEA, NEE, NEM, NEP, NET, NEU, NEV, NEW, NEWR, NEX, NEXA,\
      NFG, NFH, NFJ, NGG, NGL, NGS, NGVC, NGVT, NHA, NHF, NHI, NI, NID, NIE, NIM, NINE, NIO, NIQ, NJR, NJV, NKE, NKG, NKX, NL, NLS, NLSN, NLY, NM, NMCO,\
      NMFC, NMFX, NMI, NMM, NMR, NMS, NMT, NMY, NMZ, NNA, NNI, NNN, NNY, NOA, NOAH, NOC, NOK, NOM, NOMD, NOV, NOVA, NOW, NP, NPK, NPN, NPO, NPTN, NPV, NQP,\
      NR, NREF, NRG, NRGX, NRK, NRP, NRT, NRUC, NRZ, NS, NSA, NSC, NSCO, NSL, NSP, NSS, NTB, NTCO, NTEST, NTG, NTP, NTR, NTZ, NUE, NUM, NUO, NUS, NUV, NUW,\
      NVG, NVGS, NVO, NVR, NVRO, NVS, NVST, NVT, NVTA, NWE, NWHM, NWN, NX, NXC, NXJ, NXN, NXP, NXQ, NXR, NXRT, NYCB, NYT, NYV, NZF,\
      O, OAC, OC, OCFT, OCN, ODC, OEC, OFC, OFG, OGE, OGS, OHI, OI, OIA, OII, OIS, OKE, OLN, OLP, OMC, OMF, OMI, ONDK, ONE, ONTO,\
      OOMA, OPP, OPY, OR, ORA, ORAN, ORC, ORCC, ORCL, ORI, ORN, OSB, OSG, OSK, OTIS, OUT, OVV, OXM, OXY,\
      PAA, PAC, PACD, PACK, PAG, PAGP, PAGS, PAI, PAM, PANW, PAR, PARR, PAYC, PB, PBA, PBB, PBC, PBF, PBFX,\
      PBH, PBI, PBR, PBT, PBY, PCF, PCG, PCI, PCK, PCM, PCN, PCQ, PD, PDI, PDM, PDS, PDT, PE, PEAK, PEB, PEG,\
      PEI, PEN, PEO, PER, PFD, PFE, PFGC, PFL, PFN, PFO, PFS, PFSI, PG, PGP, PGR, PGRE, PGTI, PGZ, PH, PHD, PHG,\
      PHI, PHK, PHM, PHR, PHT, PHX, PIC, PII, PIM, PINE, PING, PINS, PIPR, PJH, PJT, PK, PKE, PKG, PKI, PKO, PKX,\
      PLAN, PLD, PLNT, PLOW, PLT, PLYM, PM, PMF, PML, PMM, PMO, PMT, PMX, PNC, PNF, PNI, PNM, PNR, PNW, POL, POR,\
      POST, PPG, PPL, PPR, PPT, PPX, PQG, PRA, PRGO, PRH, PRI, PRLB, PRMW, PRO, PROS, PRS, PRSP, PRT, PRTY, PRU, PSA,\
      PSB, PSF, PSN, PSO, PSTG, PSTL, PSV, PSX, PSXP, PTR, PTY, PUK, PUMP, PVG, PVH, PVL, PWR, PXD, PYN, PYS, PYT, PYX, PZC, PZN,\
      QD, QEP, QES, QGEN, QSR, QTS, QTWO, QUAD, QUOT, QVCC, QVCD, R, RA, RACE, RAD, RAMP, RBA, RBC, RBS, RC, RCA, RCB, RCI, RCL,\
      RCP, RCS, RCUS, RDN, RDY, RE, RELX, RENN, RES, RESI, REV, REVG, REX, REXR, REZI, RF, RFI, RFL, RFM, RFP, RGA, RGR, RGS, RGT,\
      RH, RHI, RHP, RIG, RIO, RIV, RJF, RL, RLGY, RLH, RLI, RLJ, RM, RMAX, RMD, RMED, RMG, RMI, RMM, RMT, RNG, RNGR, RNP, RNR, ROG,\
      ROK, ROL, ROP, ROYT, RPAI, RPLA, RPM, RPT, RQI, RRC, RRD, RS, RSF, RSG, RST, RTW, RTX, RUBI, RVI, RVLV, RVT, RWT, RXN, RY, RYAM, RYB, RYCE, RYI, RYN, RZA, RZB,\
      SA, SAF, SAFE, SAH, SAIC, SAIL, SALT, SAM, SAN, SAND , SAP, SAR, SAVE, SB, SBE, SBH, SBI, SBOW, SBR, SBS, SBSW, SC, SCA, SCCO, SCD,\
      SCHW, SCI, SCL, SCM, SCPE, SCS, SCU, SCVX, SCX, SD, SDRL, SE, SEAS, SEE, SEM, SERV, SF, SFB, SFE, SFL, SFTW, SFUN, SGU, SHAK, SHG,\
      SHI, SHLL, SHLX, SHO, SHOP, SHW, SI, SID, SIG, SITC, SITE, SIX, SJI, SJIJ, SJIU, SJM, SJR, SJT, SJW, SKM, SKT, SKX, SKY, SLB, SLCA,\
      SLF, SLG, SLQT, SM, SMAR, SMFG, SMG, SMHI, SMLP, SMM, SMP, SNA, SNAP, SNDR, SNE, SNN, SNP, SNR, SNV, SNX, SO, SOGO, SOI, SOJA, SOJB,\
      SOJC, SOJD, SOL, SOLN, SON, SOR, SPAQ, SPB , SPCE, SPE, SPG, SPGI, SPH, SPLP, SPN, SPOT, SPR, SPXC, SPXX, SQ, SQM, SQNS, SR, SRC,\
      SRE, SREA, SRF, SRG, SRI, SRL, SRLP, SRT, SRV, SSD, SSL, SSTK, ST, STAG, STAR , STC, STE, STG, STK, STL, STM, STN, STNG, STON, STOR,\
      STT, STWD, STZ, SU, SUI, SUM, SUN, SUP, SUPV, SUZ, SWCH, SWI, SWK, SWM, SWN, SWT, SWX, SWZ, SXC, SXI, SXT, SYF, SYK, SYX, SYY, SZC,\
      T, TAC, TAK, TAL, TALO, TAP, TARO, TBB, TBC, TBI, TCI, TCO, TCP, TCRW, TCRZ, TCS, TD, TDA, TDC, TDE, TDF, TDG, TDI, TDJ, TDOC, TDS,\
      TDW, TDY, TEAF, TECK, TEF, TEI, TEL, TEN, TEO, TEVA, TEX, TFC, TFII, TFX, TG, TGH, TGI, TGNA, TGP, TGS, TGT, THC, THG, THGA, THO, THQ,\
      THR, THS, THW, TIF, TISI, TJX, TK, TKC, TKR, TLI, TLK, TLRD, TLYS, TM, TME, TMHC, TMO, TMST, TNC, TNET, TNK, TNP, TOL, TOT, TPB, TPC,\
      TPH, TPL, TPR, TPRE, TPVG, TPVY, TPX, TPZ, TR, TRC, TREC, TREX, TRGP, TRI, TRN, TRNE, TRNO, TROX, TRP, TRQ, TRTN, TRTX, TRU, TRV, TRWH,\
      TS, TSE, TSI, TSLX, TSM, TSN, TSQ, TSU, TT, TTC, TTI, TTM, TTP, TU, TUFN, TUP, TV, TVC, TVE, TWI, TWLO, TWN, TWO, TWTR, TX, TXT, TY, TYG, TYL,\
      UA, UAA, UAN, UBA, UBER, UBP, UBS, UDR, UE, UFI, UFS, UGI, UGP, UHS, UHT, UI, UIS, UL, UMC, UMH, UN, UNF, UNFI, UNH, UNM, UNMA, UNP, UNVR, UPS,\
      URI, USA, USAC, USB, USDP, USFD, USM, USNA, USPH, USX, UTF, UTI, UTL, UVE, UVV, UZA, UZB, UZC, V, VAC, VAL, VALE, VAM, VAPO, VAR, VBF, VCIF,\
      VCRA, VCV, VEC, VEDL, VEEV, VEL, VER, VET, VFC, VGI, VGM, VGR, VHI, VICI, VIPS, VIST, VIV, VJET, VKQ, VLO, VLRS, VLT, VMC, VMI, VMO, VMW, VNCE,\
      VNE, VNO, VNTR, VOC, VOYA, VPG, VPV, VRS, VRT, VRTV, VSH, VSLR, VST, VSTO, VTA, VTN, VTR, VVI, VVNT, VVR, VVV, VZ,\
      W, WAB, WAL, WALA, WAT, WBAI, WBC, WBK, WBS, WBT, WCC, WCN, WD, WDR, WEA, WEC, WEI, WELL, WES, WEX, WF, WFC, WGO, WH,\
      WHD, WHG, WHR, WIA, WIT, WIW, WK, WLK, WLKP, WLL, WM, WMB, WMC, WMK, WMS, WMT, WNC, WNS, WOR, WORK, WOW, WPC, WPG, WPM, WPP,\
      WPX, WRB, WRE, WRI, WRK, WSM, WSO, WSR, WST, WTI, WTM, WTRG, WTRU, WTS, WTTR, WU, WUBA, WWE, WWW, WY, WYND, X, XAN, XEC, XFLT, XHR, XIN, XOM, XPO, XRF, XRX, XYF, XYL,\
      Y, YELP, YETI, YEXT, YPF, YRD, YUM, YUMC, ZBH, ZEN, ZNH, ZTO, ZTR, ZTS, ZUO, ZYME,';


      this.symbols = allSym.split(/, +/g).map((symbol) => {
        return {
          value: symbol.toUpperCase(),
          display: symbol
        };
      });
  }


  onBrowse(input:string){
    console.log(input)
    if(input == '' || null){
      this.router.navigate(['/home']);
    }
      this.router.navigate([`/stock/${input}`]);
  }


  
 
}
